spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/wechatorder?characterEncoding=utf-8
  jpa:
    show-sql: true
server:
    port: 8091
