spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/wechatorder?characterEncoding=utf-8
  jpa:
    show-sql: true
  redis:
    host: 192.168.21.244
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
    port: 8093
